
# Configuration file for the Sphinx documentation builder.

# -- Project information -----------------------------------------------------

project = 'Linear Modeling Codes'
author = 'Generated by Sphinx'

# -- General configuration ---------------------------------------------------

extensions = ['myst_parser']
templates_path = ['_templates']
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------

html_theme = 'sphinx_book_theme'
html_static_path = ['_static']
