name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Change to the branch where your "docs" folder is located
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-book-theme myst-parser

    - name: Build the Sphinx documentation
      working-directory: docs
      run: |
          sphinx-build -b html source build/html
          touch build/html/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
